-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS public.announcements
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    publish_date timestamp without time zone NOT NULL DEFAULT now(),
    "senderId" uuid,
    title character varying COLLATE pg_catalog."default" NOT NULL,
    content character varying COLLATE pg_catalog."default" NOT NULL,
    target_group character varying COLLATE pg_catalog."default",
    CONSTRAINT announcements_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.attendances
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    "studentId" uuid,
    date timestamp without time zone NOT NULL,
    status character varying COLLATE pg_catalog."default" NOT NULL,
    reason character varying COLLATE pg_catalog."default",
    CONSTRAINT attendances_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.classes
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    max_students integer,
    "teacherId" uuid,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    level character varying COLLATE pg_catalog."default",
    speciality character varying COLLATE pg_catalog."default",
    academic_year character varying COLLATE pg_catalog."default",
    CONSTRAINT classes_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.courses
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    "subjectId" uuid,
    "teacherId" uuid,
    "classId" uuid,
    semester character varying COLLATE pg_catalog."default",
    program_details character varying COLLATE pg_catalog."default",
    resources_link character varying COLLATE pg_catalog."default",
    CONSTRAINT courses_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.extra_curricular_activities
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    "supervisorId" uuid,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    description character varying COLLATE pg_catalog."default",
    CONSTRAINT extra_curricular_activities_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.grades
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    score numeric(5, 2) NOT NULL,
    max_score numeric(5, 2) NOT NULL,
    "studentId" uuid,
    "courseId" uuid,
    grade_type character varying COLLATE pg_catalog."default",
    date timestamp without time zone NOT NULL,
    teacher_comments character varying COLLATE pg_catalog."default",
    CONSTRAINT grades_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.messages
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    "timestamp" timestamp without time zone NOT NULL DEFAULT now(),
    is_read boolean NOT NULL DEFAULT false,
    "senderId" uuid,
    "receiverId" uuid,
    content character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT messages_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.performance_metrics
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    value numeric(10, 2) NOT NULL,
    "studentId" uuid,
    metric_type character varying COLLATE pg_catalog."default" NOT NULL,
    date timestamp without time zone NOT NULL,
    academic_year character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT performance_metrics_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.report_cards
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    average_score numeric(5, 2) NOT NULL,
    "studentId" uuid,
    academic_period character varying COLLATE pg_catalog."default" NOT NULL,
    global_comment character varying COLLATE pg_catalog."default",
    generated_date timestamp without time zone NOT NULL,
    CONSTRAINT report_cards_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.rooms
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    capacity integer,
    equipment jsonb,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT rooms_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.schedules
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    day_of_week integer NOT NULL,
    start_time time without time zone NOT NULL,
    end_time time without time zone NOT NULL,
    "classId" uuid,
    "teacherId" uuid,
    "subjectId" uuid,
    "roomId" uuid,
    CONSTRAINT schedules_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.student_activities
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    "studentId" uuid,
    "activityId" uuid,
    participation_date timestamp without time zone NOT NULL,
    role character varying COLLATE pg_catalog."default",
    CONSTRAINT student_activities_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.student_classes
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    "studentId" uuid,
    "classId" uuid,
    enrollment_date timestamp without time zone NOT NULL,
    status character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT student_classes_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.students
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    "userId" uuid,
    date_of_birth timestamp without time zone NOT NULL,
    gender character varying COLLATE pg_catalog."default",
    address character varying COLLATE pg_catalog."default",
    phone_number character varying COLLATE pg_catalog."default",
    enrollment_date timestamp without time zone,
    graduation_date timestamp without time zone,
    special_needs character varying COLLATE pg_catalog."default",
    CONSTRAINT students_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.subjects
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    description character varying COLLATE pg_catalog."default",
    department character varying COLLATE pg_catalog."default",
    curriculum_objectives character varying COLLATE pg_catalog."default",
    CONSTRAINT subjects_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.teachers
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    teaching_preferences jsonb,
    "userId" uuid,
    qualification character varying COLLATE pg_catalog."default",
    speciality character varying COLLATE pg_catalog."default",
    hire_date timestamp without time zone,
    name character varying COLLATE pg_catalog."default",
    CONSTRAINT teachers_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."user"
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    "firstName" character varying COLLATE pg_catalog."default" NOT NULL,
    "lastName" character varying COLLATE pg_catalog."default" NOT NULL,
    email character varying COLLATE pg_catalog."default" NOT NULL,
    password character varying COLLATE pg_catalog."default" NOT NULL,
    role character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY (id),
    CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.user_roles
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    role_name character varying COLLATE pg_catalog."default",
    permissions json,
    CONSTRAINT user_roles_pkey PRIMARY KEY (id),
    CONSTRAINT "UQ_85683c502a3882013c989f4ee35" UNIQUE (role_name)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    "isEmailVerified" boolean NOT NULL DEFAULT false,
    "isTwoFactorEnabled" boolean NOT NULL DEFAULT false,
    preferences json,
    "lastLogin" timestamp without time zone DEFAULT now(),
    email character varying COLLATE pg_catalog."default" NOT NULL,
    password character varying COLLATE pg_catalog."default" NOT NULL,
    first_name character varying COLLATE pg_catalog."default" NOT NULL,
    last_name character varying COLLATE pg_catalog."default" NOT NULL,
    profile_picture character varying COLLATE pg_catalog."default",
    status character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending'::character varying,
    "roleId" uuid NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE (email)
);

ALTER TABLE IF EXISTS public.announcements
    ADD CONSTRAINT "FK_10eecab7a1573786be41ae05cc4" FOREIGN KEY ("senderId")
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.attendances
    ADD CONSTRAINT "FK_615b414059091a9a8ea0355ae89" FOREIGN KEY ("studentId")
    REFERENCES public.students (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.classes
    ADD CONSTRAINT "FK_4b7ac7a7eb91f3e04229c7c0b6f" FOREIGN KEY ("teacherId")
    REFERENCES public.teachers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.courses
    ADD CONSTRAINT "FK_4fc71ca03df7fa563050d553c39" FOREIGN KEY ("subjectId")
    REFERENCES public.subjects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.courses
    ADD CONSTRAINT "FK_f921bd9bb6d061b90d386fa3721" FOREIGN KEY ("teacherId")
    REFERENCES public.teachers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.courses
    ADD CONSTRAINT "FK_fd1cecfbb001ebcd3a2221dff8c" FOREIGN KEY ("classId")
    REFERENCES public.classes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.extra_curricular_activities
    ADD CONSTRAINT "FK_7db2adbffdaa62b0a1be010c19d" FOREIGN KEY ("supervisorId")
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.grades
    ADD CONSTRAINT "FK_fcfc027e4e5fb37a4372e688070" FOREIGN KEY ("studentId")
    REFERENCES public.students (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.grades
    ADD CONSTRAINT "FK_ff09424ef05361e1c47fa03d82b" FOREIGN KEY ("courseId")
    REFERENCES public.courses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.messages
    ADD CONSTRAINT "FK_2db9cf2b3ca111742793f6c37ce" FOREIGN KEY ("senderId")
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.messages
    ADD CONSTRAINT "FK_acf951a58e3b9611dd96ce89042" FOREIGN KEY ("receiverId")
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.performance_metrics
    ADD CONSTRAINT "FK_6ac771e13ac26694157ac379b17" FOREIGN KEY ("studentId")
    REFERENCES public.students (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.report_cards
    ADD CONSTRAINT "FK_435d59076f1c15d98035b7cd1dd" FOREIGN KEY ("studentId")
    REFERENCES public.students (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.schedules
    ADD CONSTRAINT "FK_0749b1cdc0bbcf2d05405e3c443" FOREIGN KEY ("classId")
    REFERENCES public.classes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.schedules
    ADD CONSTRAINT "FK_651f2a89f77493526bff6115412" FOREIGN KEY ("subjectId")
    REFERENCES public.subjects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.schedules
    ADD CONSTRAINT "FK_d53e9c0b8f2c83ecaf15c9c4e60" FOREIGN KEY ("teacherId")
    REFERENCES public.teachers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.schedules
    ADD CONSTRAINT "FK_dcb26377363823daf7e1d52bcd2" FOREIGN KEY ("roomId")
    REFERENCES public.rooms (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.student_activities
    ADD CONSTRAINT "FK_011f0942ff2a749ad8fc18f1c66" FOREIGN KEY ("activityId")
    REFERENCES public.extra_curricular_activities (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.student_activities
    ADD CONSTRAINT "FK_9480b13b7e27b24f2727deda302" FOREIGN KEY ("studentId")
    REFERENCES public.students (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.student_classes
    ADD CONSTRAINT "FK_033117f841e292b127c2770693a" FOREIGN KEY ("studentId")
    REFERENCES public.students (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.student_classes
    ADD CONSTRAINT "FK_3f18cbd0ea5362b0c8727070739" FOREIGN KEY ("classId")
    REFERENCES public.classes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.students
    ADD CONSTRAINT "FK_cc65c917a3b4f2d8230c948067c" FOREIGN KEY ("userId")
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.teachers
    ADD CONSTRAINT "FK_4d8041cbc103a5142fa2f2afad4" FOREIGN KEY ("userId")
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT "FK_368e146b785b574f42ae9e53d5e" FOREIGN KEY ("roleId")
    REFERENCES public.user_roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;